import Head from "next/head";
import Login from "../component/Login";
import Sidebar from "../component/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MarthCord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar/>
      
    </div>
  );
}
